profion = {
    'cyffredin': (
        "prydferth",
        "dramodydd",
        "anifeiliaid",
        "cuddio",
        "rhôm",
        "â'th",
    ),
    'deuseiniaid': (
        "dedwydd",
        "ymadael",
        "yw",
    ),
    'deuawd ddeusill': (
        "duon",
        "eos",
        "suo",
    ),
    'triawd ddeusill': (
        "lluoedd",
        "triawd",
        "dywed",
    ),
    'lluosill acennog': (
        "cymraeg",
        "cangarŵ",
        "ffarwél",
        "dyfalbarhau",
        "dyfalbarhad",
    ),
    'w-gytsain': (
        "awen",
        "llawen",
        "bywyd",
    ),
    'gwr, gwl': (
        "gwaith",
        "gwledd",
        "wledd",
        "gwrandawiad",
        "wrandawiad",
        "gwrando",
        "gwr",
        "gwroldeb",
        "gwrhydri",
        "gŵr",
        "gwrthod",
        "gwraidd",
        "gwledydd",
        "gwneud",
        "chwerwder",
    ),
    'w-gytsain ar y diwedd': (
        "berw",
        "bedw",
        "llw",
        "pitw",  # eithriad
    ),
    'triawd talgron-talgron (T-T)': (
        "anifeiliaid",
        "piwis",
        "gwiw",
        "bwriwyd",
    ),
    'triawd talgron-lleddf (T-LL)': (
        "iaith",
        "gwaith",
        "genwair",
        "gweddiaid",
        "ffiniau",
    ),
    'triawd lleddf-talgron (LL-T)': (
        "awen",
        "distewi",
        "gwiw",
        "wiw",
        "piwis",
        "distewi",
    ),
    'triawd lleddf-lleddf (LL-LL)': (
        "daear",
        "gloyw",
    ),
    'pedwarawd': (
        "haleliwia",
        "gwrandawiad",
        "glawio",
        "gloywi",
        "ieuanc",
    ),
    'trychben': (
        "arogl",
        "hagr",
    ),
    'hollti-ia': (
        "dianc",
        "diod",
        "priod",
        "piod",
        "triawd",
        "diadell",
    ),
    'y-olau': (
        "gwely",
        "eryr",
        "benthyg",
    ),
    'wy-bondigrybwyll': (
        "gwyn",
        "trylwyr",
        'Wele',
        'Gwrol',
        'wna',
    ),
}
